server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/amock;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

amock:
  request-log:
    retention-days: 7
    sample-rate: 1.0
  rule:
    cache-max-size: 1000